//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen23.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Despacho
    {
        
        public int Id { get; set; }
        [Required]
        public System.DateTime Fecha { get; set; }
        [Required]
        public string Tipo_de_accion { get; set; }
        [Required]
        public int Cliente { get; set; }
        [Required]
        public decimal Contacto { get; set; }
        [Required]
        public int Detalle_de_producto { get; set; }
        
        public virtual Clientes Clientes { get; set; }
        
        public virtual Productos Productos { get; set; }
    }
}
